/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.merchant.views.configuration;

import com.merchant.components.listModels.ConfigurationListModel;
import com.merchant.views.MerchantPanel;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author alan
 */
public class ConfigurationPanel extends MerchantPanel {

    /**
     * Creates new form ConfigurationForm
     */
    public ConfigurationPanel() {
        initComponents();
    }
    
    @Override
    public void setParent(JInternalFrame f) {
        parent = f;
        listPrueba.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPrueba = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableConfigurations = new javax.swing.JTable();
        contentConfigurations = new javax.swing.JPanel();

        listPrueba.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        listPrueba.setModel(new ConfigurationListModel(contentConfigurations, tableConfigurations));
        listPrueba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPruebaMouseClicked(evt);
            }
        });
        listPrueba.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPruebaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPrueba);

        tableConfigurations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableConfigurations);

        contentConfigurations.setLayout(new javax.swing.BoxLayout(contentConfigurations, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentConfigurations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentConfigurations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listPruebaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPruebaMouseClicked
        
    }//GEN-LAST:event_listPruebaMouseClicked

    private void listPruebaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPruebaValueChanged
        int item = listPrueba.getSelectedIndex();
        String pathClass = ((ConfigurationListModel)listPrueba.getModel()).setConfiguration(item);
        try {
            Object o = Class.forName(pathClass).newInstance();
            contentConfigurations.setLayout(new BorderLayout());
            contentConfigurations.removeAll();
            contentConfigurations.add((JPanel)o, BorderLayout.NORTH);
            parent.repaint();
            parent.pack();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(ConfigurationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listPruebaValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentConfigurations;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listPrueba;
    private javax.swing.JTable tableConfigurations;
    // End of variables declaration//GEN-END:variables
}
