/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.merchant.views.configuration;

import com.merchant.components.tableModels.MerchantTableModel;
import com.merchant.components.tableModels.RegimenesTableModel;
import com.merchant.controllers.RegimenesController;
import com.merchant.pojos.Regimen;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author alan
 */
public class RegimenPanel extends AbstractConfigurationPanel {

    JTable tableRegimen;
    RegimenesController controller;
    Connection connection;
    boolean createRegimen = true;
    private Integer idRegimenEditar;

    /**
     * Creates new form RegimenPanel
     */
    public RegimenPanel() {
        initComponents();
    }

    public RegimenPanel(Connection connection, JTable table) {
        initComponents();
        tableRegimen = table;
        tableRegimen.setModel(new RegimenesTableModel());
        controller = new RegimenesController();
        this.connection = connection;
        initDataTable();
    }

    private void initDataTable() {
        getTableModel().initData(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreRegimen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnOpcion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setText("Regimen");

        txtNombreRegimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRegimenActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre del regimen: ");

        btnOpcion.setText("Crear");
        btnOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombreRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpcion)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionActionPerformed
        Regimen regimen = getRegimenFromForm();
        boolean exito = false;
        if (createRegimen) {
            exito = controller.create(connection, regimen);
        } else {
            exito = controller.update(connection, getRegimenFromForm(), idRegimenEditar);
        }
        if (exito) {
            initDataTable();
            clean();
            idRegimenEditar = 0;
        }
    }//GEN-LAST:event_btnOpcionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clean();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreRegimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRegimenActionPerformed
        btnOpcion.doClick();
    }//GEN-LAST:event_txtNombreRegimenActionPerformed

    private MerchantTableModel getTableModel() {
        return ((MerchantTableModel) tableRegimen.getModel());
    }

    private Regimen getRegimenFromForm() {
        Regimen regimen = new Regimen();
        regimen.descripcionRegimenFiscal = txtNombreRegimen.getText();
        return regimen;
    }

    private Regimen getRegimentFromTable(int row) {
        return (Regimen) getTableModel().getObjectByRow(row);
    }

    private void setRegimenForEdit(Regimen regimen) {
        txtNombreRegimen.setText(regimen.descripcionRegimenFiscal);
        btnOpcion.setText("Editar");
        idRegimenEditar = regimen.idregimenFiscal;
        createRegimen = false;
    }

    private void clean() {
        txtNombreRegimen.setText("");
        btnOpcion.setText("Crear");
        createRegimen = true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreRegimen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void eventEditFromJtable(int row) {
        setRegimenForEdit(getRegimentFromTable(row));
    }

    @Override
    public void eventDelFromJtable(int row) {
        Regimen regimen = getRegimentFromTable(row);
        String mensaje = "¿Estas seguro de eliminar: " + regimen.descripcionRegimenFiscal + "?";
        int opc = JOptionPane.showConfirmDialog(this, mensaje);
        if (opc == JOptionPane.OK_OPTION) {
            if (controller.delete(connection, regimen.idregimenFiscal)) {
                initDataTable();
                clean();
            }
        }
    }
}
