/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.merchant.components;

import com.merchant.views.EmpresasForm;
import java.awt.Dimension;

/**
 *
 * @author alan
 */
public class MerchantMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MerchantMainFrame
     */
    Dimension screen;

    public MerchantMainFrame() {
        initComponents();
        screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        backgroundDesktop.setBounds(10, 10, screen.width, screen.height);
        this.setSize(screen);
        setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("Merchant desktop");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        desktopMenu = new javax.swing.JPopupMenu();
        otroItem = new javax.swing.JMenuItem();
        itemEmpresas = new javax.swing.JMenuItem();
        backgroundDesktop = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        lblInicio = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");
        popupMenu.add(jMenuItem1);

        desktopMenu.setToolTipText("Menu");

        otroItem.setText("otro item");
        desktopMenu.add(otroItem);

        itemEmpresas.setText("Empresas");
        itemEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpresasActionPerformed(evt);
            }
        });
        desktopMenu.add(itemEmpresas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Desktop for users - merchant");

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setToolTipText("");
        jToolBar2.setBorderPainted(false);

        lblInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/merchant/images/cong-mod.png"))); // NOI18N
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioMouseClicked(evt);
            }
        });
        jToolBar2.add(lblInicio);

        javax.swing.GroupLayout backgroundDesktopLayout = new javax.swing.GroupLayout(backgroundDesktop);
        backgroundDesktop.setLayout(backgroundDesktopLayout);
        backgroundDesktopLayout.setHorizontalGroup(
            backgroundDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundDesktopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(backgroundDesktopLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(0, 311, Short.MAX_VALUE))
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundDesktopLayout.setVerticalGroup(
            backgroundDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundDesktopLayout.createSequentialGroup()
                .addGroup(backgroundDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundDesktop.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundDesktop.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundDesktop.setLayer(jToolBar2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseClicked
        // TODO add your handling code here:
        toggleShowMenuInicio();
    }//GEN-LAST:event_lblInicioMouseClicked

    private void itemEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpresasActionPerformed
        newInternalFrame(new EmpresasForm(), "Empresas");
    }//GEN-LAST:event_itemEmpresasActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        //System.out.println(evt.getKeyChar() + " = " + evt.getKeyCode());
    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println(evt.getKeyChar() + " = " + evt.getKeyCode());
        if (evt.getKeyCode() == 524) {
            toggleShowMenuInicio();
        }
    }//GEN-LAST:event_formKeyPressed

    private void toggleShowMenuInicio () {
        int x = lblInicio.getBounds().x;
        int y = (lblInicio.getBounds().y - (lblInicio.getHeight()/2)) - (desktopMenu.getComponentCount() * 20);
        if (!desktopMenu.isShowing()){
            desktopMenu.show(lblInicio, x, y);
        } else {
            desktopMenu.setVisible(false);
        }
    }
    
    private void newInternalFrame(final javax.swing.JPanel panel, final String internalTitle) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MerchantInternalFrame internal = new MerchantInternalFrame(internalTitle, panel);
                internal.setVisible(true);
                backgroundDesktop.add(internal);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane backgroundDesktop;
    private javax.swing.JPopupMenu desktopMenu;
    private javax.swing.JMenuItem itemEmpresas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JMenuItem otroItem;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
